title: 免费图床-图片外链-image host-image upload
author: 阿呜
email: softengineerwu@gmail.com
description: >-
  图片上传, 外链, https, 永久免费, 全球CDN加速
explain: 本站使用GitHub存储图片，不保留任何图片。图片一经上传，即可被公开查看。请自行确保图片不违反国家法律法规和GitHub相关规定。
social:
  twitter: 
  facebook: 
  instagram: 
  github: dev2007
  linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
